---
abstract: 'intelligently handle massive multi-processing on one machine'
author:
  - 'Dana M. Diederich <dana@realms.org>'
build_requires:
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Proc-Swarm
requires:
  IPC::Msg: 0
  IPC::SysV: 0
  Storable: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dana/perl-Proc-Swarm/issues
  homepage: https://github.com/dana/perl-Proc-Swarm
  repository: https://github.com/dana/perl-Proc-Swarm.git
version: 1.133280
